[general]
xpos = 100
ypos = 100
width = 750
height = 370
opacity = 1.0
auto_hide_seconds = 0
background_dim = 0.75

[paths]
systems_dir = "./systems"
mame_cfg_dir = "d:/launchbox/emulators/mame/cfg"
mame_dat = "d:/launchbox/emulators/mame/dats/mame.dat"
command_dat = "d:/launchbox/emulators/mame/dats/command.dat"
launchbox_dir = "d:/Launchbox"
